version: '3.4'
services:
  users-db-mysql:
    container_name: users-db-mysql
    build:
      context: users-api
      dockerfile: mysql.Dockerfile
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=users
      - MYSQL_ROOT_PASSWORD=root

  users-cache-redis:
    container_name: users-cache-redis
    image: redis
    command: redis-server
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVERS: "zookeeper:22888:23888"

  broker:
    image: confluentinc/cp-enterprise-kafka:5.1.2
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://broker:29092
      KAFKA_ADVERTISED_HOST_NAME: broker
      KAFKA_DELETE_TOPIC_ENABLE: true
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_BROKER_RACK: "r1"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  transaction-api-java:
    container_name: transaction-api-java
    build:
      context: transaction-api
      dockerfile: transaction.Dockerfile
    restart: on-failure
    depends_on:
      - broker
    ports:
      - "8001:8001"
    environment:
      - KAFKA_SERVER=broker
      - KAFKA_PORT=9092

  users-api-java:
    container_name: users-api-java
    build:
      context: users-api
      dockerfile: users.Dockerfile
    restart: on-failure
    depends_on:
      - users-db-mysql
      - users-cache-redis
      - broker
    ports:
      - "8000:8000"
    environment:
      - DB_URL=users-db-mysql:3306
      - TRAN_URL=http://transaction-api-java:8001
      - REDIS_URL=users-cache-redis
      - REDIS_PORT=6379
      - KAFKA_SERVER=broker
      - KAFKA_PORT=9092
