version: '3.4'
services:
  users-api-java:
    container_name: users-api-java
    build:
      context: .
      dockerfile: users.Dockerfile
    depends_on:
      - users-db-mongo
      - users-db-mysql
    ports:
      - "8000:8000"
    environment:
      - NOOP=

#      Escolha adequadamente qual banco de dados deseja utilizar descomentando uma das variáveis abaixo.
#      Durante o desenvolvimento utilizando sua IDE, mantenha ambas as variáveis de ambiente comentadas.
#      Apenas especifique no arquivo application.yml qual banco deseja utilizar. Ele está configurado para apontar para
#      o container utilizando a rede do host local.

#      - DB_URL=users-db-mongo:27017
#      - DB_URL=users-db-mysql:3306

  transaction-api-java:
    container_name: transaction-api-java
    build:
      context .
      dockerfile: transaction.Dockerfile
    ports:
      - "8001:8001"

  users-db-mysql:
    container_name: users-db-mysql
    build:
      context: .
      dockerfile: mysql.Dockerfile
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=users
      - MYSQL_ROOT_PASSWORD=root
