server.port: 8000

spring:
  application:
    name: users

  jackson:
    property-naming-strategy: SNAKE_CASE

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    hiraki:
      initialization-fail-timeout: 0
    url: jdbc:mysql://root:root@${DB_URL:localhost}/users?autoReconnect=true&useSsl=false&enabledTLSProtocols=TLSv1.2

  cache:
    type: redis

  redis:
    host: ${REDIS_URL:localhost}
    port: ${REDIS_PORT:6379}