server.port: 8000


spring:
  application:
    name: users
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


  datasource:
    url: jdbc:mysql://root:root@${DB_URL:localhost}/users?useSsl=false
